"use strict";
const D = {
  POP_CAP: 200,
  PCOLORS: ["#3f7fd8", "#d0432f", "#e0b83a", "#3fae4e", "#2fb8bf", "#a04fd0", "#d8d8d8", "#39404e"],
  ERAS: [
    { name: "黑暗時代", cost: {}, time: 0 },
    { name: "封建時代", cost: { food: 500 }, time: 25 },
    { name: "城堡時代", cost: { food: 800, gold: 250 }, time: 35 },
    { name: "帝王時代", cost: { food: 1000, gold: 800 }, time: 45 }
  ],
  DROP: { food: ["tc", "mill"], wood: ["tc", "lumber"], gold: ["tc", "mine"], stone: ["tc", "mine"] },
  UNITPALETTE: {
    vill: { tunic: "#b3945c" }, inf: { tunic: "#7a7268" }, monk: { tunic: "#cfc7b0" },
    siege: { tunic: "#7a6a4a" }, cav: { mnt: "#5a4636" }, camel: { mnt: "#967442" }, eleph: { mnt: "#8b8d95" }
  },
  UNITS: {
    vill: { name: "村民", spr: "vill", hp: 60, spd: 1.1, los: 4, cls: ["villager", "infantry"], ar: 0, rng: 0, cd: 2, atk: 1, cost: { food: 50 }, age: 0, pop: 1, bld: "tc", train: 12, carry: 10, grate: 0.5 },
    spear: { name: "長槍兵", spr: "inf", wpn: "spear", hp: 45, atk: 4, cd: 1.2, ar: 0, bonus: [["cavalry", 5], ["camel", 6]], cls: ["infantry", "melee", "spear"], spd: 1.05, rng: 0.6, los: 3, cost: { food: 25, gold: 8 }, age: 0, pop: 1, bld: "barracks", train: 14 },
    militia: { name: "民兵", spr: "inf", wpn: "sword", hp: 45, atk: 4, cd: 1.2, ar: 0, arq: 0, bonus: [], cls: ["infantry", "melee", "sword"], spd: 1.05, rng: 0.6, los: 3, cost: { food: 50, gold: 20 }, age: 1, pop: 1, bld: "barracks", train: 14 },
    longsword: { name: "長劍士", spr: "inf", wpn: "sword", hp: 55, atk: 5, cd: 1.2, ar: 1, bonus: [], cls: ["infantry", "melee", "sword"], spd: 1.05, rng: 0.6, los: 3, cost: { food: 60, gold: 25 }, age: 2, pop: 1, bld: "barracks", train: 14 },
    champion: { name: "勇士", spr: "inf", wpn: "sword", hp: 65, atk: 8, cd: 1.2, ar: 3, bonus: [], cls: ["infantry", "melee", "sword"], spd: 1.05, rng: 0.6, los: 3, cost: { food: 70, gold: 40 }, age: 3, pop: 1, bld: "barracks", train: 14 },
    axeman: { name: "擲斧兵", spr: "inf", wpn: "axe", hp: 50, atk: 7, cd: 1.4, ar: 1, bonus: [["archery", 3]], cls: ["infantry", "melee", "axe", "thrower"], spd: 1.15, rng: 2.5, los: 5, proj: "axe_", cost: { food: 55, gold: 25 }, age: 1, pop: 1, bld: "barracks", train: 14, civ: true },
    huskarl: { name: "狂戰士", spr: "inf", wpn: "axe", hp: 75, atk: 10, cd: 1.1, ar: 2, bonus: [["ranged", 7]], cls: ["infantry", "melee", "axe"], spd: 1.0, rng: 0.6, los: 3, cost: { food: 25, gold: 60 }, age: 2, pop: 1, bld: "barracks", train: 16, civ: true },
    gothaxe: { name: "哥德戰斧兵", spr: "inf", wpn: "axe", hp: 70, atk: 9, cd: 1.15, ar: 2, bonus: [["building", 4]], cls: ["infantry", "melee", "axe"], spd: 1.05, rng: 0.6, los: 3, cost: { food: 60, gold: 45 }, age: 2, pop: 1, bld: "barracks", train: 15, civ: true },
    teuton: { name: "條頓武士", spr: "inf", wpn: "sword", hp: 70, atk: 9, cd: 1.2, ar: 3, bonus: [["cavalry", 3]], cls: ["infantry", "melee", "sword"], spd: 0.95, rng: 0.6, los: 3, cost: { food: 25, gold: 65 }, age: 2, pop: 1, bld: "barracks", train: 16, civ: true },
    samurai: { name: "武士", spr: "inf", wpn: "sword", hp: 68, atk: 8, cd: 1.15, ar: 3, bonus: [["siege", 4], ["monk", 8]], cls: ["infantry", "melee", "sword"], spd: 1.1, rng: 0.6, los: 3, cost: { food: 60, gold: 50 }, age: 2, pop: 1, bld: "barracks", train: 15, civ: true },
    archer: { name: "弓兵", spr: "inf", wpn: "bow", hp: 35, atk: 4, cd: 1.5, ar: 0, bonus: [["building", 1]], cls: ["infantry", "ranged", "archer"], spd: 1.15, rng: 4.5, los: 6, proj: "arrow", cost: { food: 25, gold: 45 }, age: 1, pop: 1, bld: "archery", train: 14 },
    xbowman: { name: "弩手", spr: "inf", wpn: "xbow", hp: 40, atk: 5, cd: 1.5, ar: 1, bonus: [["building", 1]], cls: ["infantry", "ranged", "archer"], spd: 1.1, rng: 4.5, los: 6, proj: "arrow", cost: { food: 25, gold: 50 }, age: 2, pop: 1, bld: "archery", train: 14 },
    skirmisher: { name: "散兵", spr: "inf", wpn: "bow", hp: 45, atk: 3, cd: 1.5, ar: 6, bonus: [["cavalry", 5]], cls: ["infantry", "ranged", "skirmisher"], spd: 1.2, rng: 3.5, los: 6, proj: "arrow", cost: { food: 25, gold: 30 }, age: 1, pop: 1, bld: "archery", train: 14 },
    longbow: { name: "長弓兵", spr: "inf", wpn: "bow", hp: 40, atk: 6, cd: 1.55, ar: 0, bonus: [["building", 2]], cls: ["infantry", "ranged", "archer"], spd: 1.1, rng: 6, los: 8, proj: "arrow", cost: { food: 35, gold: 55 }, age: 2, pop: 1, bld: "archery", train: 16, civ: true },
    chukonu: { name: "諸葛弩", spr: "inf", wpn: "xbow", hp: 45, atk: 7, cd: 1.4, ar: 1, pierce: .5, bonus: [], cls: ["infantry", "ranged", "archer"], spd: 1.1, rng: 5, los: 7, proj: "arrow", cost: { food: 40, gold: 60 }, age: 3, pop: 1, bld: "archery", train: 16, civ: true },
    scout: { name: "斥候騎兵", spr: "cav", wpn: "none", hp: 65, atk: 3, cd: 1.3, ar: 0, bonus: [["archer", 3]], cls: ["cavalry", "melee", "scout"], spd: 1.6, rng: 0.75, los: 4, cost: { food: 35 }, age: 1, pop: 1, bld: "stable", train: 16 },
    cavalry: { name: "騎士", spr: "cav", wpn: "sword", hp: 85, atk: 10, cd: 1.4, ar: 2, bonus: [["building", 6], ["siege", 8]], cls: ["cavalry", "melee"], spd: 1.45, rng: 0.8, los: 3, cost: { food: 70, gold: 70 }, age: 2, pop: 1, bld: "stable", train: 18 },
    mamluk: { name: "馬穆魯克", spr: "cav", wpn: "sword", hp: 90, atk: 11, cd: 1.35, ar: 2, bonus: [["archer", 4]], cls: ["cavalry", "melee"], spd: 1.45, rng: 0.8, los: 3, cost: { food: 45, gold: 75 }, age: 2, pop: 1, bld: "stable", train: 18, civ: true },
    cataphract: { name: "鐵甲騎兵", spr: "cav", wpn: "sword", hp: 110, atk: 11, cd: 1.4, ar: 3, bonus: [["archer", 3]], cls: ["cavalry", "melee"], spd: 1.4, rng: 0.8, los: 3, cost: { food: 80, gold: 85 }, age: 3, pop: 1, bld: "stable", train: 20, civ: true },
    camel: { name: "駝兵", spr: "camel", wpn: "sword", hp: 85, atk: 8, cd: 1.35, ar: 0, sar: 2, bonus: [["cavalry", 7]], cls: ["camel", "melee"], spd: 1.5, rng: 0.8, los: 4, cost: { food: 70, gold: 60 }, age: 2, pop: 1, bld: "stable", train: 18 },
    mangudai: { name: "芒圖凱", spr: "cav", wpn: "bow", hp: 60, atk: 7, cd: 1.6, ar: 0, bonus: [["building", 4]], cls: ["cavalry", "ranged", "cavarcher"], spd: 1.7, rng: 4, los: 7, proj: "arrow", cost: { food: 50, gold: 75 }, age: 3, pop: 1, bld: "stable", train: 18, civ: true },
    eleph: { name: "波斯戰象", spr: "eleph", wpn: "axe", hp: 170, atk: 13, cd: 1.5, ar: 2, sar: 1, bonus: [["infantry", 4], ["building", 8]], cls: ["cavalry", "melee", "eleph"], spd: 1.15, rng: 0.9, los: 3, cost: { food: 100, gold: 80 }, age: 2, pop: 1, bld: "stable", train: 22, civ: true },
    monk: { name: "僧侶", spr: "monk", wpn: "staff", hp: 40, atk: 0, cd: 4, ar: 0, heal: 12, cls: ["monk"], spd: 1.1, rng: 3, los: 5, cost: { gold: 100 }, age: 2, pop: 1, bld: "monastery", train: 20 },
    ram: { name: "衝車", spr: "siege", sub: "ram", hp: 200, atk: 2, cd: 3, ar: 6, sar: 4, bonus: [["building", 170]], cls: ["siege", "melee", "ram"], spd: 1.3, rng: 0.9, los: 4, cost: { wood: 150 }, age: 2, pop: 1, bld: "siege", train: 20 },
    mangonel: { name: "擲石車", spr: "siege", sub: "mang", hp: 80, atk: 9, cd: 4.5, ar: 1, bonus: [["building", 4], ["siege", 5]], cls: ["siege", "ranged", "thrower"], spd: 0.9, rng: 6, los: 8, proj: "stone", splash: 0.9, cost: { wood: 100, gold: 120 }, age: 2, pop: 1, bld: "siege", train: 22 },
    treb: { name: "投石機", spr: "siege", sub: "treb", hp: 120, atk: 45, cd: 6, ar: 2, bonus: [["building", 120], ["siege", 10]], cls: ["siege", "ranged", "thrower"], aoe: 1.4, spd: 0.45, rng: 9, los: 10, proj: "stone", cost: { wood: 200, gold: 200 }, age: 3, pop: 2, bld: "siege", train: 28 }
  },
  BUILDS: {
    tc: { name: "城鎮中心", fp: [4, 4], wh: 24, style: "hip", wall: "#c8bfa2", roof: "#8a5a30", cost: { wood: 275 }, age: 0, build: 60, hp: 2200, ar: 6, los: 6, cc: true, drop: true, pop: 10, produce: ["vill"], rally: true },
    house: { name: "房屋", fp: [2, 2], wh: 14, style: "hip", wall: "#c8c2ae", roof: "#96522a", cost: { wood: 30 }, age: 0, build: 10, hp: 600, ar: 2, los: 2, pop: 5 },
    farm: { name: "農田", fp: [2, 2], wh: 0, style: "field", cost: { wood: 45 }, age: 0, build: 8, hp: 120, ar: 0, los: 1, farm: { food: 178, grow: 10 } },
    lumber: { name: "伐木場", fp: [2, 2], wh: 12, style: "hip", wall: "#a08050", roof: "#6b4523", cost: { wood: 75 }, age: 0, build: 14, hp: 700, ar: 2, los: 4, drop: true },
    mine: { name: "礦場", fp: [2, 2], wh: 12, style: "hip", wall: "#9a9aa2", roof: "#5c5c66", cost: { wood: 75 }, age: 0, build: 14, hp: 700, ar: 2, los: 4, drop: true },
    mill: { name: "磨坊", fp: [2, 2], wh: 14, style: "hip", wall: "#b8ae96", roof: "#7a4a20", cost: { wood: 60 }, age: 0, build: 14, hp: 700, ar: 2, los: 3, drop: true },
    barracks: { name: "兵營", fp: [3, 3], wh: 16, style: "hip", wall: "#a89a86", roof: "#8a3a24", cost: { wood: 125 }, age: 0, build: 20, hp: 1300, ar: 3, los: 4, produce: ["spear", "militia"], rally: true },
    archery: { name: "射箭場", fp: [3, 3], wh: 16, style: "ridg", wall: "#a89a86", roof: "#6b5a2a", cost: { wood: 125 }, age: 1, build: 20, hp: 1300, ar: 3, los: 4, produce: ["archer", "skirmisher"], rally: true },
    stable: { name: "馬廄", fp: [3, 3], wh: 15, style: "hip", wall: "#b09a7a", roof: "#6b4523", cost: { wood: 150 }, age: 1, build: 22, hp: 1400, ar: 3, los: 4, produce: ["scout"], rally: true },
    siege: { name: "攻城廠", fp: [3, 3], wh: 15, style: "hip", wall: "#9a8a6a", roof: "#5c4a20", cost: { wood: 175 }, age: 2, build: 24, hp: 1500, ar: 3, los: 4, produce: ["ram", "mangonel"], rally: true },
    armory: { name: "軍械庫", fp: [2, 2], wh: 13, style: "hip", wall: "#8f8f99", roof: "#4c4c55", cost: { wood: 100 }, age: 1, build: 16, hp: 900, ar: 3, los: 3 },
    market: { name: "市場", fp: [3, 2], wh: 14, style: "hip", wall: "#b8ae96", roof: "#a03a2a", cost: { wood: 150 }, age: 1, build: 18, hp: 1200, ar: 3, los: 4, mkt: true },
    monastery: { name: "修道院", fp: [3, 3], wh: 18, style: "hip", wall: "#c0c0c8", roof: "#4c5a7a", cost: { wood: 150, gold: 50 }, age: 2, build: 24, hp: 1500, ar: 4, los: 4, produce: ["monk"], rally: true },
    university: { name: "大學", fp: [3, 3], wh: 18, style: "hip", wall: "#c8c2ae", roof: "#3a4a3a", cost: { stone: 175 }, age: 2, build: 26, hp: 1500, ar: 4, los: 4 },
    tower: { name: "守望塔", fp: [1, 1], wh: 44, style: "flat", wall: "#a8a8b0", cost: { wood: 30, stone: 25 }, age: 1, build: 20, hp: 960, ar: 8, los: 9, tower: { atk: 6, rng: 6, cd: 1.6, proj: "arrow" } },
    castle: { name: "城堡", fp: [4, 4], wh: 30, style: "castle", wall: "#adb0b8", cost: { wood: 200, gold: 100, stone: 120 }, age: 2, build: 55, hp: 3200, ar: 10, los: 10, pop: 10, tower: { atk: 8, rng: 7, cd: 2.2, proj: "arrow", shots: 2 } },
    wall: { name: "城牆", fp: [1, 1], wh: 16, style: "flat", wall: "#9a9aa2", cost: { wood: 5, stone: 8 }, age: 1, build: 5, hp: 840, ar: 8, los: 1 },
    gate: { name: "城門", fp: [2, 1], wh: 15, style: "flat", wall: "#9a9aa2", cost: { wood: 40 }, age: 1, build: 8, hp: 840, ar: 8, los: 2, openable: true },
    dock: { name: "碼頭", fp: [3, 2], wh: 0, style: "dock", cost: { wood: 125 }, age: 1, build: 18, hp: 900, ar: 2, los: 5, drop: true },
    wonder: { name: "奇觀", fp: [4, 4], wh: 30, style: "wonder", wall: "#d8d2c0", cost: { wood: 400, gold: 300, stone: 300 }, age: 3, build: 140, hp: 4400, ar: 10, los: 5 }
  },
  TECHS: {
    loom: { name: "織布機", bld: "tc", age: 0, cost: { food: 35 }, t: 9, eff: { units: ["vill"], hp: .25 } },
    wheelbarrow: { name: "手推車", bld: "tc", age: 1, cost: { food: 125, wood: 175 }, t: 15, eff: { units: ["vill"], spd: .08, carry: 3 } },
    handcart: { name: "手推車", bld: "tc", age: 2, cost: { food: 150, wood: 200 }, t: 17, eff: { units: ["vill"], carry: 5 } },
    horsecollar: { name: "馬頸圈", bld: "mill", age: 1, cost: { food: 100 }, t: 15, eff: { eco: { farmMul: .25 } } },
    heavyplow: { name: "重犁", bld: "mill", age: 2, cost: { food: 200 }, t: 17, eff: { eco: { farmMul: .3 } } },
    croprotation: { name: "輪耕制", bld: "mill", age: 3, cost: { food: 300 }, t: 19, eff: { eco: { farmMul: .35 } } },
    forging: { name: "鍛造", bld: "armory", age: 1, cost: { food: 150 }, t: 15, eff: { units: ["militia", "longsword", "champion", "teuton", "samurai", "huskarl", "gothaxe", "axeman"], atk: 1 } },
    iron: { name: "鑄鐵術", bld: "armory", age: 2, cost: { food: 250 }, t: 17, eff: { units: ["militia", "longsword", "champion", "teuton", "samurai", "huskarl", "gothaxe", "axeman"], atk: 1 } },
    blast: { name: "鼓風爐", bld: "armory", age: 3, cost: { food: 400 }, t: 20, eff: { units: ["militia", "longsword", "champion", "teuton", "samurai", "huskarl", "gothaxe", "axeman"], atk: 1 } },
    scale1: { name: "鱗甲", bld: "armory", age: 2, cost: { food: 150 }, t: 15, eff: { units: ["militia", "longsword", "champion", "teuton", "samurai", "huskarl", "gothaxe", "axeman", "spear"], ar: 1 } },
    chain1: { name: "鎖子甲", bld: "armory", age: 3, cost: { food: 300 }, t: 18, eff: { units: ["militia", "longsword", "champion", "teuton", "samurai", "huskarl", "gothaxe", "axeman", "spear"], ar: 1 } },
    fletch1: { name: "裝羽术", bld: "armory", age: 1, cost: { food: 100 }, t: 15, eff: { units: ["archer", "xbowman", "skirmisher", "longbow", "chukonu", "mangudai"], atk: 1 } },
    fletch2: { name: "倒刺箭", bld: "armory", age: 2, cost: { food: 200 }, t: 17, eff: { units: ["archer", "xbowman", "skirmisher", "longbow", "chukonu", "mangudai"], atk: 1 } },
    fletch3: { name: "破甲箭", bld: "armory", age: 3, cost: { food: 350 }, t: 19, eff: { units: ["archer", "xbowman", "skirmisher", "longbow", "chukonu", "mangudai"], atk: 1 } },
    padarcher: { name: "緩衝衣", bld: "armory", age: 2, cost: { food: 120 }, t: 15, eff: { units: ["archer", "xbowman", "skirmisher", "longbow", "chukonu", "mangudai"], ar: 1 } },
    ringarcher: { name: "環甲", bld: "armory", age: 3, cost: { food: 250 }, t: 17, eff: { units: ["archer", "xbowman", "skirmisher", "longbow", "chukonu", "mangudai"], ar: 1 } },
    bloodlines: { name: "血統", bld: "stable", age: 2, cost: { food: 225 }, t: 15, eff: { units: ["scout", "cavalry", "mamluk", "cataphract", "camel", "mangudai"], hp: .35 } },
    ballistics: { name: "彈道學", bld: "university", age: 3, cost: { food: 175, gold: 175 }, t: 15, eff: { units: ["archer", "xbowman", "skirmisher", "longbow", "chukonu", "mangudai", "mangonel", "treb"], moving: 1 } },
    masonry: { name: "磚石技術", bld: "university", age: 1, cost: { food: 100 }, t: 15, eff: { barm: 1 } },
    architecture: { name: "建築學", bld: "university", age: 2, cost: { food: 200 }, t: 17, eff: { bhp: .25 } },
    embrasures: { name: "射孔", bld: "university", age: 3, cost: { stone: 200 }, t: 17, eff: { towatk: 2 } },
    heatedshot: { name: "熱瀝青", bld: "university", age: 3, cost: { wood: 100, gold: 200 }, t: 17, eff: { towrng: 1 } },
    murderholes: { name: "殺人洞", bld: "university", age: 2, cost: { stone: 150 }, t: 15, eff: { towar: 2 } },
    redemption: { name: "救贖", bld: "monastery", age: 3, cost: { gold: 275 }, t: 17, eff: { units: ["monk"], heal: 8 } },
    atonement: { name: "贖罪", bld: "monastery", age: 3, cost: { gold: 225 }, t: 17, eff: { units: ["monk"], cd: -1.5 } },
    yeomen: { name: "自耕農", bld: "tc", age: 2, cost: { food: 200 }, t: 17, eff: { units: ["archer", "skirmisher"], rng: 1 }, civ: "britons" },
    beardedaxe: { name: "闊斧", bld: "tc", age: 2, cost: { food: 200 }, t: 17, eff: { units: ["axeman"], rng: 1 }, civ: "franks" },
    gothicfury: { name: "哥德之怒", bld: "tc", age: 3, cost: { food: 350 }, t: 18, eff: { units: ["gothaxe", "huskarl"], atk: 2 }, civ: "goths" },
    chancophorae: { name: "盾牆戰術", bld: "tc", age: 3, cost: { food: 350 }, t: 18, eff: { units: ["teuton"], ar: 2 }, civ: "teutons" },
    berserkhelm: { name: "狂戰士之盔", bld: "tc", age: 3, cost: { food: 300, gold: 100 }, t: 18, eff: { units: ["huskarl"], hp: .5 }, civ: "vikings" },
    mammothcull: { name: "獵象術", bld: "tc", age: 3, cost: { food: 300 }, t: 18, eff: { bonusCls: [["eleph", 6]], units: ["spear", "camel", "skirmisher"] }, civ: "saracens" },
    tithe: { name: "什一稅", bld: "tc", age: 2, cost: { food: 250 }, t: 17, eff: { eco: { carry: 2 } }, civ: "persians" },
    steppebred: { name: "草原良駒", bld: "tc", age: 3, cost: { food: 300 }, t: 17, eff: { units: ["mangudai", "camel", "scout", "cavalry"], spd: .08 }, civ: "mongols" },
    greatwall: { name: "長城", bld: "tc", age: 3, cost: { stone: 200 }, t: 18, eff: { bhp: .25 }, civ: "chinese" },
    yedo: { name: "江戶遺風", bld: "tc", age: 3, cost: { food: 350 }, t: 18, eff: { units: ["samurai"], atk: 1, ar: 1 }, civ: "japanese" },
    greekfire: { name: "希臘火", bld: "tc", age: 3, cost: { gold: 250 }, t: 18, eff: { towatk: 2, towrng: 1 }, civ: "byzantines" },
    cauldron: { name: "凱爾特戰鍋", bld: "tc", age: 3, cost: { food: 300 }, t: 18, eff: { units: ["gallinknight"], hp: .3, ar: 2 }, civ: "celts" }
  },
  CIVS: {
    britons: { name: "不列顛", color: "#3f7fd8", units: ["longbow"], tech: "yeomen", desc: "弓兵射程+1", passives: [{ units: ["archer", "xbowman", "longbow", "skirmisher"], rng: 1 }] },
    franks: { name: "法蘭西", color: "#d0432f", units: ["axeman"], tech: "beardedaxe", desc: "騎兵生命+25%", passives: [{ units: ["scout", "cavalry", "mamluk", "cataphract"], hp: .25 }] },
    goths: { name: "哥德", color: "#5c646e", units: ["gothaxe"], tech: "gothicfury", desc: "步兵攻擊+1", passives: [{ units: ["militia", "longsword", "champion", "spear"], atk: 1 }] },
    teutons: { name: "條頓", color: "#3a3f4a", units: ["teuton"], tech: "chancophorae", desc: "步兵護甲+1", passives: [{ units: ["militia", "longsword", "champion", "spear", "teuton"], ar: 1 }] },
    vikings: { name: "維京", color: "#c05a2a", units: ["huskarl"], tech: "berserkhelm", desc: "村民搬運+2", passives: [{ eco: { carry: 2 } }] },
    saracens: { name: "薩拉森", color: "#3fae4e", units: ["mamluk"], tech: "mammothcull", desc: "騎兵對弓兵+1", passives: [{ units: ["cavalry", "mamluk", "cataphract"], bonusAdd: [["archer", 1]] }] },
    persians: { name: "波斯", color: "#e0b83a", units: ["eleph"], tech: "tithe", desc: "農田產量+25%", passives: [{ eco: { farmMul: .25 } }] },
    mongols: { name: "蒙古", color: "#8a6d2f", units: ["mangudai"], tech: "steppebred", desc: "騎兵與攻城移速+10%", passives: [{ units: ["scout", "cavalry", "camel", "mangudai", "mangonel", "treb", "ram"], spd: .1 }] },
    chinese: { name: "中國", color: "#b05a8a", units: ["chukonu"], tech: "greatwall", desc: "村民移速+8%", passives: [{ units: ["vill"], spd: .08 }] },
    japanese: { name: "日本", color: "#a84a4a", units: ["samurai"], tech: "yedo", desc: "漁獲+50%", passives: [{ eco: { fishMul: 1 } }] },
    byzantines: { name: "拜占庭", color: "#7a5ab0", units: ["cataphract"], tech: "greekfire", desc: "對騎兵反制+2", passives: [{ units: ["spear", "skirmisher", "camel"], bonusAdd: [["cavalry", 2]] }] },
    celts: { name: "凱爾特", color: "#2f8f5f", units: ["gallinknight"], tech: "cauldron", desc: "步兵移速+8%", passives: [{ units: ["militia", "longsword", "champion", "spear"], spd: .08 }] }
  }
};
D.UNITS.gallinknight = { name: "高盧騎士", spr: "cav", wpn: "sword", hp: 95, atk: 10, cd: 1.35, ar: 1, bonus: [["archer", 3]], cls: ["cavalry", "melee"], spd: 1.5, rng: 0.8, los: 3, cost: { food: 70, gold: 70 }, age: 2, pop: 1, bld: "stable", train: 18, civ: true };


